#-------------------------------
# Site Settings
title: CastroForGeorgia
logo: '/images/logo.png' # You can add own logo. For example '/images/logo.png'.
logo_dark: '/images/logo.png'
description: Andres Castro, un defensor de la gente en el 5.º Distrito Congresional de Georgia. 
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Inicio'
      url: '/'
    - title: 'Acerca de'
      url: '/about/'
    - title: "Por qué me postulo"
      url: '/blog/why-im-running/'
    - title: 'Políticas'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Contacto'
      url: 'https://actionnetwork.org/forms/connect-with-andres-share-your-vision'

#-------------------------------
# Author Settings
author:
  author_name: Andres Castro
  author_avatar: '/images/about-me-photo-zoom.jpg'

#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_role: "Candidato para la Cámara de Representantes de EE.UU. (GA-05) ∙ Luchando por las familias trabajadoras, viviendas asequibles y dignidad económica"
  hero_title: "¡Hola! Soy Andres <img src=\"/images/about-me-photo-zoom.jpg\" alt=\"Andres Castro Picture\" loading=\"lazy\"> <br> Luchando por el 5.º Distrito de Georgia"
  hero_description: "Juntos, podemos construir un futuro que funcione para todos—donde la equidad, la justicia y las oportunidades sean más que promesas, sean realidades. Creemos un cambio significativo para las familias trabajadoras de Georgia."
  hero_button_text: "Únete al Movimiento"
  hero_button_link: "https://actionnetwork.org/forms/connect-with-andres-share-your-vision"

#-------------------------------
# Projects Section Settings
projects:
  enable: true
  projects_title: Políticas
  projects_description: Explora nuestra visión de un futuro más justo y equitativo para el 5.º Distrito de Georgia. Juntos, construiremos un futuro próspero y equitativo.

#-------------------------------
# Blog Section Settings
blog:
  enable: true
  blog_title: Blog
  blog_description: Construyamos un futuro que funcione para todos.

#-------------------------------
# About Section Settings
about:
  enable: true
  about_image: "/images/about-me-photo.jpg"
  about_title: "Juntos por el Cambio"
  about_description: "Construyamos un futuro donde cada familia en el 5.º Distrito de Georgia tenga acceso a oportunidades, equidad y justicia. Únete a mí en la lucha por soluciones audaces que eleven a las familias trabajadoras, protejan los derechos civiles y creen un gobierno que realmente funcione para todos nosotros."

#-------------------------------
# Faq (Frequently Asked Questions) Settings
faq:
  enable: true
  faq_title: "¿Necesitas respuestas?"
  faq_description: "Conoce a Andres Castro y su compromiso con la creación de una comunidad más justa e inclusiva en el 5.º Distrito Congresional de Georgia."
  faq_items:
    - title: "¿Qué motivó a Andres Castro a postularse para un cargo?"
      description: "Andres Castro se motivó a postularse debido a su frustración con el liderazgo demócrata actual, que, según él, ha dejado de priorizar las necesidades de la gente. Ve líderes que no escuchan, actúan con lentitud y no cumplen las promesas hechas a las familias trabajadoras. Andres se está postulando para brindar un liderazgo audaz e intransigente que ponga a los residentes del 5.º Distrito Congresional de Georgia en primer lugar."

    - title: "¿Quién es Andres Castro?"
      description: "Andres Castro es un orgulloso hijo del área metropolitana de Atlanta, con raíces profundas en Marietta, Powder Springs y Atlanta. Creciendo en la pobreza, conoció de primera mano las luchas de las familias trabajadoras. A través de determinación y trabajo duro, Andres se convirtió en Ingeniero de Software Sénior, donde perfeccionó su experiencia en el uso de tecnología para resolver problemas complejos. Ahora, como candidato para Representante de EE.UU. en el 5.º Distrito Congresional de Georgia, Andres se enfoca en crear soluciones para viviendas asequibles, justicia económica y gobernanza transparente, asegurando oportunidades y equidad para todos."

    - title: "¿Cuáles son las principales prioridades políticas de Andres Castro?"
      description: "Las prioridades de Andres Castro incluyen soluciones audaces para abordar desigualdades sistémicas: viviendas asequibles mediante programas como La Garantía de Vivienda para los Trabajadores, atención médica universal para garantizar el acceso a todos, programas de reentrenamiento laboral conscientes de la automatización y responsabilidad corporativa para que las grandes empresas cumplan con estándares justos de salarios e impuestos. Con su experiencia técnica, Andres también defiende la ética en la IA y soluciones innovadoras y equitativas para empoderar a los trabajadores y comunidades."

    - title: "¿Cómo pueden los simpatizantes involucrarse en la campaña de Andres Castro?"
      description: "Los simpatizantes pueden participar como voluntarios en actividades como tocar puertas, hacer llamadas telefónicas y organizar eventos, asistir a reuniones comunitarias y compartir los mensajes de la campaña en redes sociales. También puedes suscribirte al boletín de la campaña para mantenerte informado y tomar acción. Tu apoyo y participación son fundamentales para impulsar un cambio significativo en el 5.º Distrito Congresional de Georgia."

#-------------------------------
# Social Links
social:
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://www.instagram.com/castroforgeorgia/"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/CastroForGeorgia"}
- {icon: "fa-brands fa-bluesky", name: "Bluesky", link: "https://bsky.app/profile/castroforgeorgia.bsky.social"}
- {icon: "fa-brands fa-huggingface", name: "Huggingface", link: "https://huggingface.co/CastroForGeorgia"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social"}
# Other icons can be found at https://fontawesome.com/icons

#-------------------------------
# Google Analytics
google-analytics: G-8XLD5HNY8Q
